# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: rc-permalink

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    urlPublicKey: thePubKeyofUrlEncryption

# The `functions` block defines what code to deploy
functions:
  mediaProxy:
    handler: build/proxy.get
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /proxy/{mediaUrl}
          method: get
          cors: true
  encodeUrl:
    handler: build/encode.get
    description: Encode the original media url
    events:
      - http:
          path: /encode/{mediaUrl}
          method: get
